### ISSUE TITLE
Error kafka.errors.NoBrokersAvailable: NoBrokersAvailable

### ISSUE THREAD

**Issue by Stefen-Taime** [team-data-science/document-streaming#2]
I have error when i try to execute on postman the 127.0.0.1:8000/invoiceitem 

error:
File "/home/stefen/anaconda/lib/python3.9/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/stefen/anaconda/lib/python3.9/site-packages/kafka/client_async.py", line 900, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable

**Comment by andkret** [comment]
Hi Stefan, please post this in the Discord. 
This way we can chat about what you have done exactly and discuss debugging options.
The last two lines here are the most important ones. 
There are no Kafka brokers available for your API to write into.
I would check this with a local consumer and producer within the Kafka container.
Let's discuss further on Discord

**Comment by Stefen-Taime** [comment]
Hello, I am subscribed to the training, but I don't have the link Discord

**Comment by andkret** [comment]
The link is in the introduction lesson of the Academy: https://learndataengineering.com/courses/1309984/lectures/36819996

I can't post the direct link here because this is public.
